import { useNavigate } from "react-router-dom";

// ─── Content ──────────────────────────────────────────────────────────────────
const LAST_UPDATED = "June 24, 2025";
const CONTACT_EMAIL = "prepnpitch@gmail.com";
// const CONTACT_PHONE = "+91 82916 19774";
const BUSINESS_NAME = "PrepNPitch";
const BRAND = "PrepNPitch";

const CONTENT = {
  privacy: {
    title: "Privacy Policy",
    subtitle: "How we collect, use, and protect your information.",
    sections: [
      {
        heading: "1. Information We Collect",
        body: [
          "When you sign in with Google, we collect your name and email address via Google OAuth.",
          "When you use our tools, we temporarily process content you provide — such as GitHub repository URLs, resume PDFs, and job descriptions — solely to generate AI-powered results.",
          "We do not store the full text of your resume or job descriptions on our servers beyond the duration of a single request.",
          "Payment information (card details, bank info) is handled entirely by Razorpay and is never stored on PrepNPitch servers.",
        ],
      },
      {
        heading: "2. How We Use Your Information",
        body: [
          "To create and manage your account.",
          "To provide, maintain, and improve our AI-powered interview preparation services.",
          "To process payments and send transaction confirmations.",
          "To communicate service updates or respond to support requests.",
          "We do not sell, rent, or trade your personal information to any third party.",
        ],
      },
      {
        heading: "3. Data Storage & Security",
        body: [
          "Account data (name, email, subscription plan) is stored in Google Firebase Firestore, which is encrypted at rest and in transit.",
          "Payment records are stored with Razorpay in compliance with PCI-DSS standards.",
          "We use industry-standard security practices and HTTPS for all data transmission.",
        ],
      },
      {
        heading: "4. Cookies & Analytics",
        body: [
          "We may use browser storage (localStorage) to remember your dark/light mode preference.",
          "We do not currently use third-party tracking cookies or advertising networks.",
        ],
      },
      {
        heading: "5. Your Rights",
        body: [
          "You may request deletion of your account and associated data at any time by emailing " + CONTACT_EMAIL + ".",
          "You may revoke Google sign-in access from your Google account settings.",
          "Requests will be processed within 14 business days.",
        ],
      },
      {
        heading: "6. Changes to This Policy",
        body: [
          "We may update this Privacy Policy periodically. The 'Last Updated' date at the top will reflect any changes. Continued use of the service after changes constitutes acceptance.",
        ],
      },
      {
        heading: "7. Contact",
        body: [
          "For any privacy-related queries, email us at " + CONTACT_EMAIL + ".",
        ],
      },
    ],
  },

  terms: {
    title: "Terms of Service",
    subtitle: "Please read these terms carefully before using PrepNPitch.",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: [
          "By accessing or using PrepNPitch (prepnpitch.vercel.app), you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.",
        ],
      },
      {
        heading: "2. Description of Service",
        body: [
          BRAND + " is an AI-powered interview preparation platform offering: GitHub project explanation generation, resume analysis and ATS scoring, job description match scoring, and mock interview practice tools.",
          "Services are available under a Free tier (limited usage) and a paid Pro tier (unlimited usage).",
        ],
      },
      {
        heading: "3. User Accounts",
        body: [
          "You must sign in with a valid Google account to access most features.",
          "You are responsible for maintaining the security of your account.",
          "You must not use the service for any unlawful purpose or in violation of these terms.",
          "We reserve the right to suspend or terminate accounts that violate these terms.",
        ],
      },
      {
        heading: "4. Subscriptions & Payments",
        body: [
          "Pro plans are billed as a one-time or recurring charge in Indian Rupees (INR) via Razorpay.",
          "All prices are inclusive of applicable taxes unless stated otherwise.",
          "By completing a payment, you agree to our Refund Policy.",
        ],
      },
      {
        heading: "5. AI-Generated Content Disclaimer",
        body: [
          "All content generated by PrepNPitch is AI-produced and provided for informational and practice purposes only.",
          "We do not guarantee the accuracy, completeness, or fitness of AI outputs for any particular purpose.",
          "You should independently verify any information before using it in professional settings.",
        ],
      },
      {
        heading: "6. Intellectual Property",
        body: [
          "The PrepNPitch brand, logo, and platform code are the property of " + BUSINESS_NAME + ".",
          "Content you provide (resumes, project links) remains your own. You grant us a limited license to process it solely to deliver the service.",
        ],
      },
      {
        heading: "7. Limitation of Liability",
        body: [
          "PrepNPitch is provided 'as is' without warranty of any kind. To the maximum extent permitted by law, " + BUSINESS_NAME + " is not liable for any indirect, incidental, or consequential damages arising from your use of the service.",
          "Our total liability to you shall not exceed the amount you paid in the 30 days prior to the claim.",
        ],
      },
      {
        heading: "8. Governing Law",
        body: [
          "These terms are governed by the laws of India. Any disputes will be subject to the exclusive jurisdiction of the courts in Mumbai, Maharashtra.",
        ],
      },
      {
        heading: "9. Changes to Terms",
        body: [
          "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes your acceptance of the new terms.",
        ],
      },
      {
        heading: "10. Contact",
        body: [
          "For any questions regarding these Terms, email " + CONTACT_EMAIL + ".",
        ],
      },
    ],
  },

  refund: {
    title: "Refund & Cancellation Policy",
    subtitle: "Please read this policy carefully before making a purchase.",
    sections: [
      {
        heading: "1. Refund Eligibility Window",
        body: [
          "We offer a 48-hour refund window from the time of purchase, subject to the usage conditions in Section 2.",
          "Refund requests made after 48 hours of purchase will not be entertained under any circumstances.",
          "To request a refund within the eligible window, email " + CONTACT_EMAIL + " with your registered email address, payment reference number, and reason for the request.",
        ],
      },
      {
        heading: "2. Usage-Based Refund Restriction (Important)",
        body: [
          "A refund will NOT be issued — even within the 48-hour window — if any of the following usage thresholds have been crossed:",
          "• More than 3 AI-generated project explanations (ExplainMyProject) have been created.",
          "• More than 3 resume analysis reports (Resume Checker) have been generated.",
          "• More than 3 job match reports (Job Match Score) have been generated.",
          "• More than 5 total AI feature uses across any combination of tools.",
          "This policy exists to prevent misuse where the service is fully consumed before a refund is requested. Usage data is tracked and verified on our end.",
        ],
      },
      {
        heading: "3. Non-Refundable Situations",
        body: [
          "Refunds will not be issued in any of the following cases, regardless of the time elapsed:",
          "• Usage thresholds in Section 2 have been exceeded.",
          "• The request is made after 48 hours of purchase.",
          "• Dissatisfaction with AI-generated output quality (AI results are inherently variable; we encourage using the Free tier before upgrading).",
          "• Change of mind after substantial use of the service.",
          "• Account suspension or termination due to a violation of our Terms of Service.",
        ],
      },
      {
        heading: "4. Cancellation",
        body: [
          "You may cancel future renewals (for monthly plans) at any time by emailing " + CONTACT_EMAIL + " with subject line 'Cancel Subscription'.",
          "Cancellation stops future billing. You retain Pro access until the end of your current paid billing period.",
          "No prorated refund is given for unused days after the cancellation date.",
        ],
      },
      {
        heading: "5. Failed / Duplicate Payments",
        body: [
          "If your bank was debited but Pro access was not activated, email " + CONTACT_EMAIL + " with your payment reference number within 7 days. Such cases will be resolved within 7–10 business days.",
          "Duplicate charges (same plan charged twice within 24 hours) will be reviewed and refunded in full.",
        ],
      },
      {
        heading: "6. How to Request a Refund",
        body: [
          "Email: " + CONTACT_EMAIL,
          // "Phone / WhatsApp: " + CONTACT_PHONE,
          "Include: your registered email, Razorpay payment ID, date of purchase, and reason for refund.",
          "We will respond within 2 business days. Approved refunds are processed within 5–7 business days to your original payment method.",
        ],
      },
    ],
  },

  contact: {
    title: "Contact Us",
    subtitle: "We're here to help. Reach out anytime.",
    sections: [],
  },
};

// ─── Section renderer ─────────────────────────────────────────────────────────
function Section({ heading, body, dark }) {
  const textMain = dark ? "#f0f0f0" : "#0a0a0a";
  const textSub  = dark ? "#888"    : "#555";
  const border   = dark ? "#1a1a1a" : "#e5e5e5";

  return (
    <div style={{ borderBottom: `1px solid ${border}`, paddingBottom: 28, marginBottom: 28 }}>
      <h2 style={{ fontFamily: "'Syne', sans-serif", fontWeight: 700, fontSize: 16, color: textMain, marginBottom: 12 }}>
        {heading}
      </h2>
      <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 }}>
        {body.map((line, i) => (
          <li key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start", fontSize: 14, color: textSub, lineHeight: 1.75 }}>
            <span style={{ color: "#F5A623", marginTop: 5, flexShrink: 0, fontSize: 8 }}>●</span>
            {line}
          </li>
        ))}
      </ul>
    </div>
  );
}

// ─── Contact Page body ────────────────────────────────────────────────────────
function ContactBody({ dark }) {
  const cardBg   = dark ? "#0d0d0d" : "#ffffff";
  const border   = dark ? "#1a1a1a" : "#e5e5e5";
  const textMain = dark ? "#f0f0f0" : "#0a0a0a";
  const textSub  = dark ? "#888"    : "#555";

  const cards = [
    { icon: "✉", label: "Email", value: CONTACT_EMAIL, href: `mailto:${CONTACT_EMAIL}` },
    // { icon: "📞", label: "Phone / WhatsApp", value: CONTACT_PHONE, href: `tel:+918291619774` },
  ];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 40 }}>

      {/* About */}
      <div style={{ background: cardBg, border: `1px solid ${border}`, borderRadius: 16, padding: "28px 32px" }}>
        <div style={{ display: "inline-block", fontSize: 11, letterSpacing: "0.15em", color: "#F5A623", fontFamily: "'JetBrains Mono', monospace", marginBottom: 14, textTransform: "uppercase" }}>
          About PrepNPitch
        </div>
        <h2 style={{ fontFamily: "'Syne', sans-serif", fontWeight: 700, fontSize: 22, color: textMain, marginBottom: 14 }}>
          AI-powered interview prep for developers
        </h2>
        <p style={{ fontSize: 14, color: textSub, lineHeight: 1.8, marginBottom: 12 }}>
          PrepNPitch is a software-as-a-service platform that helps developers prepare for technical job interviews. It offers four core tools:
        </p>
        <ul style={{ listStyle: "none", padding: 0, display: "flex", flexDirection: "column", gap: 10 }}>
          {[
            "ExplainMyProject — Generates interview-ready project narratives from your GitHub repository.",
            "Resume Checker — Scores your resume for ATS compatibility and rewrites weak bullet points.",
            "Job Match Score — Compares your resume against a job description and gives a match percentage with skill gaps.",
            "Mock Interviews — AI-powered voice interview simulations (coming soon).",
          ].map((t, i) => (
            <li key={i} style={{ display: "flex", gap: 10, fontSize: 14, color: textSub, lineHeight: 1.7 }}>
              <span style={{ color: "#F5A623", flexShrink: 0 }}>✓</span> {t}
            </li>
          ))}
        </ul>
        <p style={{ fontSize: 13, color: dark ? "#555" : "#aaa", marginTop: 16 }}>
          Operated by {BUSINESS_NAME} · {BRAND} is an independent product, not affiliated with any employer or recruitment agency.
        </p>
      </div>

      {/* Contact cards */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>
        {cards.map(c => (
          <a key={c.label} href={c.href}
            style={{ background: cardBg, border: `1px solid ${border}`, borderRadius: 16, padding: "24px 28px", textDecoration: "none", display: "flex", flexDirection: "column", gap: 8, transition: "border-color 0.2s" }}
            onMouseEnter={e => e.currentTarget.style.borderColor = "#F5A623"}
            onMouseLeave={e => e.currentTarget.style.borderColor = border}
          >
            <span style={{ fontSize: 28 }}>{c.icon}</span>
            <span style={{ fontSize: 11, fontFamily: "'JetBrains Mono', monospace", color: "#F5A623", letterSpacing: "0.1em", textTransform: "uppercase" }}>{c.label}</span>
            <span style={{ fontSize: 15, fontWeight: 600, color: textMain }}>{c.value}</span>
          </a>
        ))}
      </div>

      {/* Response time */}
      <p style={{ fontSize: 13, color: dark ? "#444" : "#bbb", textAlign: "center" }}>
        We typically respond within 24 hours on business days.
      </p>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function LegalPage({ dark, type }) {
  const navigate  = useNavigate();
  const content   = CONTENT[type];
  const bg        = dark ? "#050505" : "#f5f5f0";
  const textMain  = dark ? "#f0f0f0" : "#0a0a0a";
  const textSub   = dark ? "#666"    : "#888";
  const border    = dark ? "#1a1a1a" : "#e5e5e5";
  const cardBg    = dark ? "#0d0d0d" : "#ffffff";

  const legalLinks = [
    { label: "Privacy Policy",  path: "/privacy" },
    { label: "Terms of Service", path: "/terms"  },
    { label: "Refund Policy",   path: "/refund"  },
    { label: "Contact Us",      path: "/contact" },
  ];

  if (!content) return null;

  return (
    <div style={{ minHeight: "100vh", background: bg, transition: "background 0.3s" }}>
      <main style={{ maxWidth: 780, margin: "0 auto", padding: "48px 24px 80px" }}>

        {/* Breadcrumb */}
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 36, fontSize: 12, color: textSub, fontFamily: "'JetBrains Mono', monospace" }}>
          <button onClick={() => navigate("/")}
            style={{ background: "none", border: "none", cursor: "pointer", color: "#F5A623", fontSize: 12, fontFamily: "inherit", padding: 0 }}>
            Home
          </button>
          <span>/</span>
          <span>{content.title}</span>
        </div>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <h1 style={{ fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: "clamp(28px, 4vw, 44px)", color: textMain, marginBottom: 12 }}>
            {content.title}
          </h1>
          <p style={{ fontSize: 15, color: textSub, lineHeight: 1.7, marginBottom: 16 }}>{content.subtitle}</p>
          {type !== "contact" && (
            <div style={{ fontSize: 11, fontFamily: "'JetBrains Mono', monospace", color: dark ? "#333" : "#ccc" }}>
              Last updated: {LAST_UPDATED} &nbsp;·&nbsp; {BRAND}, operated by {BUSINESS_NAME}
            </div>
          )}
        </div>

        {/* Body */}
        <div style={{ background: cardBg, border: `1px solid ${border}`, borderRadius: 20, padding: "36px 40px" }}>
          {type === "contact" ? (
            <ContactBody dark={dark} />
          ) : (
            content.sections.map((s, i) => (
              <Section key={i} heading={s.heading} body={s.body} dark={dark} />
            ))
          )}
        </div>

        {/* Nav to other legal pages */}
        <div style={{ marginTop: 40, display: "flex", flexWrap: "wrap", gap: 12, justifyContent: "center" }}>
          {legalLinks.filter(l => l.path !== `/${type}`).map(l => (
            <button key={l.label}
              onClick={() => navigate(l.path)}
              style={{ background: "none", border: `1px solid ${border}`, color: textSub, borderRadius: 8, padding: "8px 18px", fontSize: 12, cursor: "pointer", fontFamily: "'DM Sans', sans-serif", transition: "all 0.2s" }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = "#F5A623"; e.currentTarget.style.color = "#F5A623"; }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = border; e.currentTarget.style.color = textSub; }}
            >
              {l.label}
            </button>
          ))}
        </div>

      </main>
    </div>
  );
}
